# Generated by Django 3.2.19 on 2023-05-11 17:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='подробное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='краткое описание'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'lng', 'lat')},
        ),
    ]
